#!/usr/bin/env python3
"""
Script per estrarre e ottimizzare cookie YouTube
Estrae i cookie dal browser e li filtra per mantenere solo YouTube/Google
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

def check_yt_dlp():
    """Verifica se yt-dlp è installato"""
    if shutil.which('yt-dlp'):
        return True
    try:
        import yt_dlp
        return True
    except ImportError:
        return False

def extract_cookies(browser='firefox', output_file='cookies_raw.txt'):
    """Estrae i cookie dal browser usando yt-dlp"""
    print(f"📥 Estraggo cookie da {browser}...")
    
    # Prova yt-dlp direttamente
    yt_dlp_cmd = shutil.which('yt-dlp')
    if not yt_dlp_cmd:
        # Prova con Python
        try:
            import yt_dlp
            yt_dlp_cmd = None  # Useremo Python module
        except ImportError:
            print("❌ ERRORE: yt-dlp non trovato!")
            print("   Installa con: pip install yt-dlp")
            return False
    
    # Costruisci comando
    # NOTA: yt-dlp richiede un URL anche quando si estraggono solo i cookie
    # Usiamo un URL YouTube valido come placeholder (non verrà scaricato)
    if yt_dlp_cmd:
        # yt-dlp eseguibile trovato
        cmd = [
            yt_dlp_cmd,
            '--cookies-from-browser', browser,
            '--cookies', output_file,
            '--no-download',  # Non scaricare, solo estrai cookie
            'https://www.youtube.com/watch?v=dQw4w9WgXcQ'  # URL dummy
        ]
    else:
        # Usa Python module
        cmd = [
            sys.executable, '-m', 'yt_dlp',
            '--cookies-from-browser', browser,
            '--cookies', output_file,
            '--no-download',  # Non scaricare, solo estrai cookie
            'https://www.youtube.com/watch?v=dQw4w9WgXcQ'  # URL dummy
        ]
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60  # Aumentato timeout
        )
        
        # yt-dlp può restituire exit code != 0 anche se i cookie sono stati estratti
        # Controlla se il file è stato creato
        if os.path.exists(output_file) and os.path.getsize(output_file) > 0:
            file_size = os.path.getsize(output_file)
            print(f"✅ Cookie estratti: {output_file} ({file_size:,} bytes)")
            return True
        else:
            print(f"❌ ERRORE durante estrazione:")
            if result.stdout:
                print(f"   STDOUT: {result.stdout[:500]}")
            if result.stderr:
                print(f"   STDERR: {result.stderr[:500]}")
            if result.returncode != 0:
                print(f"   Exit code: {result.returncode}")
            return False
    except subprocess.TimeoutExpired:
        print("❌ ERRORE: Timeout durante estrazione")
        return False
    except Exception as e:
        print(f"❌ ERRORE: {e}")
        import traceback
        traceback.print_exc()
        return False

def optimize_cookies(input_file='cookies_raw.txt', output_file='cookies.txt'):
    """Ottimizza i cookie mantenendo solo YouTube/Google"""
    print(f"🔧 Ottimizzo cookie...")
    
    if not os.path.exists(input_file):
        print(f"❌ File non trovato: {input_file}")
        return False
    
    # Domini da mantenere
    keep_domains = [
        'youtube.com',
        'youtu.be',
        'google.com',
        'googleusercontent.com',
        'gstatic.com',
        'googleapis.com',
        'googlevideo.com',
        'ggpht.com',
        'googleadservices.com',
        'doubleclick.net',
        'googlesyndication.com',
        'google-analytics.com',
        'gmail.com',
        'googlemail.com',
        'accounts.google.com',
        'myaccount.google.com',
    ]
    
    kept_count = 0
    removed_count = 0
    
    try:
        with open(input_file, 'r', encoding='utf-8', errors='ignore') as infile:
            lines = infile.readlines()
        
        with open(output_file, 'w', encoding='utf-8') as outfile:
            # Scrivi header Netscape
            outfile.write("# Netscape HTTP Cookie File\n")
            outfile.write("# This file is generated by yt-dlp.  Do not edit.\n\n")
            
            for line in lines:
                line = line.strip()
                
                # Mantieni commenti e righe vuote
                if not line or line.startswith('#'):
                    outfile.write(line + '\n')
                    continue
                
                # Parse Netscape cookie format
                # domain, flag, path, secure, expiration, name, value
                parts = line.split('\t')
                if len(parts) < 6:
                    removed_count += 1
                    continue
                
                domain = parts[0].strip()
                
                # Controlla se il dominio va mantenuto
                should_keep = False
                for keep_domain in keep_domains:
                    if domain == keep_domain or domain.endswith('.' + keep_domain):
                        should_keep = True
                        break
                
                if should_keep:
                    outfile.write(line + '\n')
                    kept_count += 1
                else:
                    removed_count += 1
        
        input_size = os.path.getsize(input_file)
        output_size = os.path.getsize(output_file)
        reduction = ((input_size - output_size) / input_size * 100) if input_size > 0 else 0
        
        print(f"✅ Ottimizzazione completata:")
        print(f"   Cookie mantenuti: {kept_count}")
        print(f"   Cookie rimossi: {removed_count}")
        print(f"   Dimensione: {input_size:,} bytes → {output_size:,} bytes ({reduction:.1f}% riduzione)")
        
        return True
        
    except Exception as e:
        print(f"❌ ERRORE durante ottimizzazione: {e}")
        return False

def generate_base64(input_file='cookies.txt', output_file='cookies_base64.txt'):
    """Genera file Base64 per Render"""
    print(f"📦 Genero file Base64...")
    
    if not os.path.exists(input_file):
        print(f"❌ File non trovato: {input_file}")
        return False
    
    try:
        import base64
        
        with open(input_file, 'rb') as f:
            content = f.read()
        
        base64_content = base64.b64encode(content).decode('ascii')
        
        with open(output_file, 'w') as f:
            f.write(base64_content)
        
        file_size = os.path.getsize(output_file)
        print(f"✅ File Base64 generato: {output_file} ({file_size:,} bytes)")
        print(f"   Pronto per essere copiato in COOKIES_BASE64 su Render")
        
        return True
        
    except Exception as e:
        print(f"❌ ERRORE durante generazione Base64: {e}")
        return False

def main():
    """Funzione principale"""
    print("=" * 70)
    print("🍪 Estrazione e Ottimizzazione Cookie YouTube")
    print("=" * 70)
    print()
    
    # Verifica yt-dlp
    if not check_yt_dlp():
        print("❌ yt-dlp non trovato!")
        print("   Installa con: pip install yt-dlp")
        sys.exit(1)
    
    # Directory di lavoro (root del progetto)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    os.chdir(project_root)
    
    # File temporanei e finali
    cookies_raw = 'cookies_raw.txt'
    cookies_optimized = 'cookies.txt'
    cookies_base64 = 'cookies_base64.txt'
    
    # Chiedi browser (default: firefox)
    print("Browser disponibili:")
    print("  1. firefox (default)")
    print("  2. chrome")
    print("  3. edge")
    print("  4. safari")
    print("  5. opera")
    print("  6. brave")
    print()
    
    browser_choice = input("Scegli browser [1-6, default=1]: ").strip()
    browser_map = {
        '1': 'firefox',
        '2': 'chrome',
        '3': 'edge',
        '4': 'safari',
        '5': 'opera',
        '6': 'brave',
    }
    browser = browser_map.get(browser_choice, 'firefox')
    
    print()
    print("=" * 70)
    print()
    
    # Step 1: Estrai cookie
    if not extract_cookies(browser, cookies_raw):
        print()
        print("❌ Estrazione fallita. Verifica che:")
        print(f"   - {browser} sia installato")
        print(f"   - {browser} sia stato aperto almeno una volta")
        print(f"   - yt-dlp sia installato: pip install yt-dlp")
        sys.exit(1)
    
    print()
    
    # Step 2: Ottimizza cookie
    if not optimize_cookies(cookies_raw, cookies_optimized):
        print()
        print("❌ Ottimizzazione fallita")
        sys.exit(1)
    
    print()
    
    # Step 3: Genera Base64
    if not generate_base64(cookies_optimized, cookies_base64):
        print()
        print("❌ Generazione Base64 fallita")
        sys.exit(1)
    
    print()
    print("=" * 70)
    print("✅ COMPLETATO!")
    print("=" * 70)
    print()
    print("File generati:")
    print(f"  📄 {cookies_optimized} - Cookie ottimizzati (usa questo per locale)")
    print(f"  📄 {cookies_base64} - Cookie Base64 (copia in COOKIES_BASE64 su Render)")
    print()
    print("Prossimi passi:")
    print("  1. Verifica che cookies.txt funzioni in locale")
    print("  2. Copia il contenuto di cookies_base64.txt")
    print("  3. Vai su Render Dashboard → Environment")
    print("  4. Aggiorna COOKIES_BASE64 con il nuovo contenuto")
    print("  5. Riavvia il servizio su Render")
    print()
    
    # Pulisci file temporaneo
    if os.path.exists(cookies_raw):
        try:
            os.remove(cookies_raw)
            print(f"🧹 File temporaneo rimosso: {cookies_raw}")
        except:
            pass
    
    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print()
        print("\n❌ Interrotto dall'utente")
        sys.exit(1)
    except Exception as e:
        print()
        print(f"❌ ERRORE: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

